import './globals.css'
import { Readex_Pro } from 'next/font/google'

const readex_pro = Readex_Pro({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={readex_pro.className}>{children}</body>
    </html>
  )
}
